config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  get '/users_list', to: 'users#list', as: :users_list
  root to: 'users#index'

  resources :messages, except: [:new] do
    collection do
      get '/count_messages', to: 'messages#get_message_count'
      get '/load_messages', to: 'messages#load_messages', as: :load_messages
      get '/new/:rxuser_id', to: 'messages#new', as: :new
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      cannot [:new, :create, :update, :destroy, :edit], :User
      can [:index, :show, :list], :User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :tx_user, class_name: 'User', foreign_key: 'txuser_id'
  belongs_to :rx_user, class_name: 'User', foreign_key: 'rxuser_id'

  def self.get_messages current_user, opponent_id
    sql_string = 'txuser_id = ? AND rxuser_id = ? OR txuser_id = ? AND rxuser_id = ?'
    Message.where(sql_string, opponent_id, current_user, current_user, opponent_id).order(created_at: :desc)
  end

  def mark_as_read
    update(read: true)
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :validatable

  has_many :in_messages, class_name: 'Message', foreign_key: :rxuser_id
  has_many :out_messages, class_name: 'Message', foreign_key: :txuser_id

  validates :username, presence: true, length: { maximum: 64 }, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: [:create, :update]}, uniqueness: true

  def admin?
    admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end

  rescue_from ActiveRecord::RecordNotFound do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_url, :alert => exception.message }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:edit, keys: [:username, :email, :password, :current_password, :admin, :about])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :about])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password, :admin, :about])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :find_message, only: [:show, :edit]

  def index
    @messages = Message.where(rxuser_id: current_user.id).order(created_at: :desc)
  end

  def show
    @message.mark_as_read if @message.rxuser_id == current_user.id
    @messages_history = Message.get_messages current_user.id, @message.txuser_id
  end

  def load_messages
    @messages = Message.where(rxuser_id: current_user.id).order(created_at: :desc)
    render :_messages, :layout => false
  end

  def new
    @message = Message.new
    @message.txuser_id = params[:rxuser_id]
    @message.rxuser_id = current_user.id
    @messages_history = Message.get_messages current_user.id, params[:rxuser_id]
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.new(message_params)
    if current_user.id.to_s != params[:id]
      @message.rxuser_id = params[:id]
      @message.txuser_id = current_user.id
      if @message.save
        flash[:notice] = 'Message sent'
        redirect_to :messages
      else
        render :show
      end
    else
      redirect_to :messages, alert: "You can't send a message yourself"
    end
  end

  def get_message_count
    render json: { count: Message.where(rxuser_id: current_user.id, read: false).count }
  end

  private

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:id, :message)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :only => [:new, :create, :update, :destroy, :edit]

  before_action :find_user, only: [:show, :edit, :destroy, :update]

  def index
  end

  def list
    @users = User.all.where.not(id: current_user.id)
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.assign_attributes(user_params)
    if @user.valid? && @user.save
      redirect_to users_path, notice: 'Profile was successfully created'
    else
      redirect_to new_user_path, alert: 'Something went wrong!'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "Delete success."
  end

  def update
    @user.assign_attributes(user_params)
    if @user.valid? && @user.save
      redirect_to users_path, notice: 'Profile was successfully edited'
    else
      redirect_to edit_user_path(@user.id), alert: 'Something went wrong!'
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end
    params.require(:user).permit(:username, :email, :about, :admin, :blocked, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
#header-wrapper
  nav.navbar.navbar-default.navbar-inverse
    .container-fluid
      .navbar-header
        = link_to '/', {class: 'navbar-brand'} do
          span.glyphicon.glyphicon.glyphicon-home
          span.app-title  TestMessenger

      #main-menu.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li= link_to 'Users', users_list_path, :class => 'navbar-link'
            li.messages-info-block
              = link_to messages_path do
                span.glyphicon.glyphicon-envelope
                span.found-messages.hidden
                  = "You have "
                  span.count_messages
                  = " unread messages."
                span.notfound-messages.hidden You don't have new messages.
            li
              = link_to current_user.email, edit_user_registration_path, :class => 'navbar-link'
            li
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
          - else
            li
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
            li
              = link_to "Login", new_user_session_path, :class => 'navbar-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TestMessenger
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #header
      == render :partial => 'layouts/header'
    .container-fluid
      - if notice
        p.alert.alert-success= notice
      - if alert
        p.alert.alert-danger= alert
      = yield

app/views/messages/_form.html.slim
.panel.panel-default
  .panel-heading = "From #{@message.rx_user.username} ==> To #{@message.tx_user.username}"
  .panel-body
    i Messages history
    - unless @messages_history.blank?
      .message-history
        = render partial: "messages/messages_history", locals: {messages_history: @messages_history}
    - else
      p Nothing to show
    - unless @message.tx_user.blocked == true
      = form_for(@message, url: message_path(@message.tx_user.id), html: {method: :put}) do |f|
        .form-group
          = f.label :message
          = f.text_area :message, class: 'form-control', value: ''
        = f.submit 'Send', class: "btn btn-primary"
    - else
      p.alert.alert-danger= "You can't send message #{@message.tx_user.username}. User blocked."

app/views/messages/_messages.html.slim
- @messages.each do |message|
  tr class=[message.read ? '' : 'info']
    td = message.tx_user.username
    td = message.rx_user.username
    td = message.message[0..128]
    td = message.created_at.strftime('%c')
    td
      = link_to 'Read & Reply', message_path(message.id), class: 'btn btn-sm btn-default'

app/views/messages/_messages_history.html.slim
- @messages_history.each do |message|
  .message-item-block.clearfix
    .message-item.clearfix class=[message.rxuser_id == current_user.id ? 'income':'outcome pull-right']
      span.message-date
        small=message.created_at.strftime('%T')
      span.message-item-body= message.message

app/views/messages/index.html.slim
h2
  = 'Latest messages'
  a.btn.btn-default.pull-right.refresh-button
    .glyphicon.glyphicon-refresh
    span Refresh
- unless @messages.blank?
  table.table
    thead
      tr
        th From
        th To
        th Short message
        th Date
        th
    tbody.messages_list
    = render partial: "messages/messages", locals: {messages: @messages}
- else
  p Nothing to show

app/views/messages/new.html.slim
h2 Send message
= render partial: "messages/form", locals: {message: @message, messages_history: @messages_history}

app/views/messages/show.html.slim
h2 Reply to message
= render partial: "messages/form", locals: {message: @message, messages_history: @messages_history}

app/views/users/edit.html.slim
.row
  .col-md-3.col-md-offset-4
    .panel.panel-default.devise-bs
      .panel-heading
        h4
          = t('.title', default: "Edit #{@user.username.to_s.humanize}")
      .panel-body
        = form_for(@user, url: user_path(@user.id), html: { method: :put }) do |f|
          .form-group
            = f.label :username
            = f.text_field :username, autofocus: true, class: 'form-control'
          .form-group
            = f.label :email
            = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password
            i
              | (
              = t('.leave_blank_if_you_don_t_want_to_change_it', default: "leave blank if you don't want to change it")
              | )
            = f.password_field :password, autocomplete: "off", class: 'form-control'
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'
          .form-group
            = f.label :about
            i
              | (
              = t('.about_information', default: 'Short information about you')
              | )
            = f.text_area :about, class: 'form-control'
          .checkbox
            = f.label :admin do
              = f.check_box :admin
              = t('.admin_checkbox', default: 'Admin permission')
          .checkbox
            = f.label :blocked do
              = f.check_box :blocked
              = t('.admin_checkbox', default: 'Blocked')
          = f.submit t('.update', default: 'Update'), class: 'btn btn-primary'
    p
      = link_to t('.cancel_my_account', default: 'Delete account'), user_path(@user.id), data: { confirm: t('.are_you_sure', default: "Are you sure?") }, method: :delete
    p
      = link_to t('.back', default: 'Back'), :back

app/views/users/index.html.slim
.jumbotron.text-center
  h2= "Hello! #{current_user.username.to_s.humanize}"
  p Welcome to the TestMessanger.

app/views/users/list.html.slim
h2 Users list
table.table
  thead
    tr
      th User name
      th About
      th Active
      th Role
      th
  tbody.users_list
    - @users.each do |user|
      tr
        td= user.username
        td= user.about
        td= user.blocked == false ? 'Active' : 'Blocked'
        td= user.admin == true ? 'Admin' : 'User'
        th
          = link_to 'Send message', new_messages_path(user.id), class: 'btn btn-sm btn-default'
          - if can? :update, @users
            = link_to 'Edit', edit_user_path(user.id), class: 'btn btn-sm btn-default'
- if can? :create, @users
  = link_to 'Add', new_user_path, class: 'btn btn-sm btn-default'

app/views/users/new.html.slim
.row
  .col-md-3.col-md-offset-4
    .panel.panel-default.devise-bs
      .panel-heading
        h4
          = t('.title', default: "New")
      .panel-body
        = form_for(@user, url: create_user_path, html: { method: :post }) do |f|
          .form-group
            = f.label :username
            = f.text_field :username, autofocus: true, class: 'form-control'
          .form-group
            = f.label :email
            = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password
            i
              | (
              = t('.leave_blank_if_you_don_t_want_to_change_it', default: "leave blank if you don't want to change it")
              | )
            = f.password_field :password, autocomplete: "off", class: 'form-control'
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: 'form-control'
          .form-group
            = f.label :about
            i
              | (
              = t('.about_information', default: 'Short information about you')
              | )
            = f.text_area :about, class: 'form-control'
          .checkbox
            = f.label :admin do
              = f.check_box :admin
              = t('.admin_checkbox', default: 'Admin permission')
          .checkbox
            = f.label :blocked do
              = f.check_box :blocked
              = t('.admin_checkbox', default: 'Blocked')
          = f.submit t('.update', default: 'Update'), class: 'btn btn-primary'
    p
      = link_to t('.back', default: 'Back'), :back